apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-registration-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-registration
  template:
    metadata:
      labels:
        app: flask-registration
    spec:
      containers:
      - name: flask-registration-container
        image: your-dockerhub-username/flask-registration-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-registration-service
spec:
  type: NodePort
  selector:
    app: flask-registration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Optional fixed port for testing
